import { requireEnv } from '@/lib/env';
import { makeId, nowIso } from '@/lib/id';
import type { BacktestResult, StrategySpec } from '@/lib/types';
import { gzipSync } from 'node:zlib';

const PLAYBOOK_BASE_URL = 'https://api.bitget.com';

export async function runPlaybookBacktest(runId: string, strategy: StrategySpec): Promise<BacktestResult> {
  const accessKey = requireEnv('PLAYBOOK_ACCESS_KEY');
  const draftId = await uploadTemporaryPlaybook(accessKey, strategy);
  const playbookRunId = await dispatchRun(accessKey, draftId);
  const completed = await pollRun(accessKey, playbookRunId);
  const metrics = completed.metrics_output ?? completed.signal_output?.[0]?.metrics ?? {};
  const report = completed.backtest_report ?? {};

  return {
    backtest_id: playbookRunId,
    run_id: runId,
    provider: 'bitget_playbook',
    period: report.period_start && report.period_end ? `${report.period_start} to ${report.period_end}` : 'playbook-run-period',
    pnl: Number(metrics.total_return_pct ?? metrics.pnl ?? 0),
    sharpe: Number(metrics.sharpe_ratio ?? metrics.sharpe ?? 0),
    win_rate: Number(metrics.win_rate ?? 0),
    max_drawdown: Number(metrics.max_drawdown_pct ?? metrics.max_drawdown ?? 0),
    trade_count: Number(metrics.total_trades ?? metrics.trade_count ?? 0),
    raw_summary_ref: `playbook:${draftId}:${playbookRunId}`,
    created_at: nowIso(),
  };
}

async function uploadTemporaryPlaybook(accessKey: string, strategy: StrategySpec) {
  const archive = buildPlaybookArchive(strategy);
  const form = new FormData();
  form.append('package', new Blob([archive], { type: 'application/gzip' }), `${strategy.strategy_id}.tar.gz`);

  const response = await fetch(`${PLAYBOOK_BASE_URL}/api/v1/playbook/upload`, {
    method: 'POST',
    headers: { 'ACCESS-KEY': accessKey },
    body: form,
  });

  if (!response.ok) throw new Error(`Playbook upload failed: ${response.status}`);
  const data = await response.json();
  const draftId = data.draft_id ?? data.version_id ?? data.playbook_id;
  if (!draftId) throw new Error('Playbook upload response missing draft_id');
  return String(draftId);
}

async function dispatchRun(accessKey: string, draftId: string) {
  const response = await fetch(`${PLAYBOOK_BASE_URL}/api/v1/playbook/run`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'ACCESS-KEY': accessKey,
    },
    body: JSON.stringify({ version_id: draftId }),
  });

  if (!response.ok) throw new Error(`Playbook run dispatch failed: ${response.status}`);
  const data = await response.json();
  if (!data.run_id) throw new Error('Playbook dispatch response missing run_id');
  return String(data.run_id);
}

async function pollRun(accessKey: string, playbookRunId: string) {
  const url = `${PLAYBOOK_BASE_URL}/api/v1/playbook/run?run_id=${encodeURIComponent(playbookRunId)}`;
  for (let attempt = 0; attempt < 30; attempt += 1) {
    const response = await fetch(url, { headers: { 'ACCESS-KEY': accessKey } });
    if (!response.ok) throw new Error(`Playbook run poll failed: ${response.status}`);
    const data = await response.json();
    if (data.status === 'completed') return data;
    if (data.status === 'failed') throw new Error(data.failure_reason || 'Playbook run failed');
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
  throw new Error('Playbook run timed out after 60 seconds');
}

function buildPlaybookArchive(strategy: StrategySpec) {
  const symbol = sanitizeSymbol(strategy.structured_strategy.symbol);
  const packageName = `tradetrace-${strategy.strategy_id}`.toLowerCase().replace(/_/g, '-').slice(0, 63);
  const files = new Map<string, string>();
  files.set('manifest.yaml', manifestYaml(packageName, symbol, strategy));
  files.set('backtest.yaml', backtestYaml(symbol));
  files.set('src/main.py', mainPy());
  files.set('src/strategy.py', strategyPy());
  return gzipSync(createTar(files));
}

function manifestYaml(name: string, symbol: string, strategy: StrategySpec) {
  const description = `TradeTrace generated audit playbook for ${symbol}`;
  return `name: ${name}
display_name: "TradeTrace ${symbol} Audit Playbook"
version: "1.0.0"
description: "${description}"
long_description: |
  Temporary Playbook generated by TradeTrace Flight Recorder to create a managed
  backtest artifact for an AI trading-agent run. Original strategy:
  ${strategy.raw_prompt.replace(/\n/g, ' ').slice(0, 500)}
market_type: contract
trading_symbols: ["${symbol}"]
tags: ["tradetrace", "audit", "hackathon"]

decision_mode: deterministic
backtest_support: full
runtime_profile: deterministic
execution_mode: signal_only
follow_trade_supported: false

strategy_config:
  trading_symbols: ["${symbol}"]
  fast_period: 12
  slow_period: 26
  leverage: 1
  margin_budget: "100"
`;
}

function backtestYaml(symbol: string) {
  const base = symbol.replace('USDT', '');
  return `venue:
  name: BINANCE
  account_type: MARGIN
  oms_type: NETTING
  starting_balances:
    - amount: 100000
      currency: USDT

strategy:
  module: strategy
  class: EmaCrossStrategy
  config_class: EmaCrossStrategyConfig
  config:
    order_id_tag: "001"
    trade_size: "0.01"
    fast_period: 12
    slow_period: 26

execution:
  start: "2024-01-01T00:00:00Z"
  end: "2024-04-01T00:00:00Z"

instrument:
  id: ${symbol}.BINANCE
  kind: perpetual
  raw_symbol: ${symbol}
  base_currency: ${base}
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 2
  size_precision: 3
  price_increment: "0.01"
  size_increment: "0.001"
  lot_size: "0.001"
  maker_fee: "0.0002"
  taker_fee: "0.0005"
  bar_type: ${symbol}.BINANCE-1-HOUR-LAST-EXTERNAL
`;
}

function mainPy() {
  return `import math
from typing import Any
from getagent import backtest, data, runtime


def _sanitize(value: Any) -> Any:
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def run() -> None:
    cfg = runtime.manifest.get("strategy_config", {}) or {}
    symbols = cfg.get("trading_symbols") or ["BTCUSDT"]
    symbol = symbols[0]
    bars = data.crypto.futures.kline(symbol=symbol, interval="1h", limit=1000)
    replay_frame = backtest.prepare_frame(bars, datetime_index="date")
    if replay_frame.empty:
        runtime.emit_signal(action="watch", symbol=symbol, confidence=0.0, metrics={"rows": 0})
        return
    instrument_key = f"{symbol}.BINANCE"
    result = backtest.run(ohlcv_data={instrument_key: replay_frame}, spec=runtime.backtest_spec)
    summary = result.summary or {}
    metrics = {
        "total_return_pct": _sanitize(result.total_return_pct),
        "sharpe_ratio": _sanitize(result.sharpe_ratio),
        "max_drawdown_pct": _sanitize(result.max_drawdown_pct),
        "win_rate": _sanitize(result.win_rate),
        "total_trades": _sanitize(result.total_trades),
        "profit_factor": _sanitize(result.profit_factor),
        "starting_balance": summary.get("starting_balance"),
        "rows": len(replay_frame),
    }
    action = "long" if (result.total_return_pct or 0) > 0 else "watch"
    runtime.emit_signal(action=action, symbol=symbol, confidence=_sanitize(result.win_rate) or 0.0, metrics=metrics)


if __name__ == "__main__":
    run()
`;
}

function strategyPy() {
  return `from dataclasses import dataclass


@dataclass
class EmaCrossStrategyConfig:
    order_id_tag: str = "001"
    trade_size: str = "0.01"
    fast_period: int = 12
    slow_period: int = 26


class EmaCrossStrategy:
    def __init__(self, config: EmaCrossStrategyConfig):
        self.config = config
`;
}

function sanitizeSymbol(symbol: string) {
  const upper = symbol.toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (upper.endsWith('USDT')) return upper;
  return 'BTCUSDT';
}

function createTar(files: Map<string, string>) {
  const chunks: Buffer[] = [];
  for (const [name, content] of files) {
    const body = Buffer.from(content, 'utf8');
    chunks.push(tarHeader(name, body.length));
    chunks.push(body);
    chunks.push(Buffer.alloc((512 - (body.length % 512)) % 512));
  }
  chunks.push(Buffer.alloc(1024));
  return Buffer.concat(chunks);
}

function tarHeader(name: string, size: number) {
  const header = Buffer.alloc(512, 0);
  header.write(name, 0, 100, 'utf8');
  header.write('0000644\0', 100, 8, 'ascii');
  header.write('0000000\0', 108, 8, 'ascii');
  header.write('0000000\0', 116, 8, 'ascii');
  writeOctal(header, size, 124, 12);
  writeOctal(header, Math.floor(Date.now() / 1000), 136, 12);
  header.fill(' ', 148, 156);
  header.write('0', 156, 1, 'ascii');
  header.write('ustar\0', 257, 6, 'ascii');
  header.write('00', 263, 2, 'ascii');
  const checksum = header.reduce((sum, byte) => sum + byte, 0);
  writeOctal(header, checksum, 148, 8);
  return header;
}

function writeOctal(buffer: Buffer, value: number, offset: number, length: number) {
  const text = value.toString(8).padStart(length - 1, '0').slice(0, length - 1) + '\0';
  buffer.write(text, offset, length, 'ascii');
}
